/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/oauth/reissue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Access Token 재발급 API
     * @description Refresh Token을 이용하여 새로운 Access Token을 발급합니다.
     *     Refresh Token은 Cookie에서 자동으로 읽어옵니다.
     */
    post: operations['reissueToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 로그아웃 API */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/memo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 메모 전체 조회(대시보드)
     * @description 메모를 전체 조회합니다.
     *     - labelIds가 있으면 해당 라벨이 포함된 메모만 조회합니다.
     *     - 커서 기반 페이지네이션을 지원합니다.
     *     - 각 메모는 대표 이미지 1개(presigned URL)와
     *       이미지/파일 개수 정보를 포함합니다.
     */
    get: operations['getMemos'];
    put?: never;
    /**
     * 메모 작성
     * @description 메모를 작성합니다.
     *     이미지/파일은 presigned URL을 통해 S3에 업로드 완료 후
     *     s3Key 정보를 함께 전달해야 합니다.
     */
    post: operations['createMemo'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/memo/presigned-urls': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 메모 이미지/파일 presigned URL 발급
     * @description 메모 생성 전에 S3에 업로드할 이미지/파일용 presigned PUT URL을 발급합니다.
     *     업로드 완료 후 s3Key를 메모 생성 API에 전달해야 합니다.
     */
    post: operations['issuePresignedUrls'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/memo/ai': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * AI가 생성한 메모 전체 조회(대시보드)
     * @description AI가 생성한 메모를 전체 조회합니다.
     *     - labelIds가 있으면 해당 라벨이 포함된 메모만 조회합니다.
     *     - 커서 기반 페이지네이션을 지원합니다.
     *     - 각 메모는 대표 이미지 1개(presigned URL)와
     *       이미지/파일 개수 정보를 포함합니다.
     */
    get: operations['getAiMemos'];
    put?: never;
    /**
     * AI가 만든 메모 저장
     * @description AI 응답 결과를 기반으로 메모를 등록요청을 하는 API입니다.
     *     제목과 본문을 분리해서 전달해야 합니다.
     */
    post: operations['createAiMemo'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/chat-rooms': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * AI 채팅방 전체 조회
     * @description 로그인한 사용자의 AI 채팅방 목록을 조회합니다.
     */
    get: operations['getChatRooms'];
    put?: never;
    /**
     * AI 채팅방 생성
     * @description 새로운 AI 채팅방을 생성합니다.
     */
    post: operations['createChatRoom'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/chat-rooms/{chatRoomId}/chat': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * AI 채팅 응답 생성
     * @description 선택한 메모들을 기반으로 RAG를 수행하여
     *     AI 응답을 생성합니다.
     *
     *     - chatRoomId : AI 대화 세션 ID
     *     - userPrompt : 사용자의 질문
     *     - option     : AI 처리 전략 (MERGE, STRUCTURE, SUMMARY)
     *     - memoIds    : 참조할 메모 ID 목록
     *
     *     채팅방(chatRoom) 단위로 대화 컨텍스트가 유지됩니다.
     */
    post: operations['generateMemoAi'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/chat-rooms/{chatRoomId}/chat/for-plan': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * [기획 의사결정용] AI 응답 생성 + 품질 지표 평가
     * @description 기획에서 정의한 System Prompt를 기반으로 AI 응답을 생성하고,
     *     생성된 응답에 대해 품질 지표를 함께 반환합니다.
     *
     *     ---
     *     기본 동작
     *     - 이 API에서는 option 값은 실제 처리 로직에는 사용되지 않습니다.
     *     - AI의 동작 방식은 전적으로 systemPrompt에 의해 결정됩니다.
     *     - memoIds는 RAG 컨텍스트로 사용되며,
     *       systemPrompt는 최상위 SYSTEM 메시지로 적용됩니다.
     *
     *     ---
     *     응답 품질 평가 지표 설명
     *
     *     1. Relevance Score (0.0 ~ 1.0)
     *     - 응답이 사용자 요청 의도와 얼마나 잘 부합하는지 나타내는 지표
     *     - 0.8↑ 적합, 0.5~0.8 부분적 적합, 0.5↓ 부적합
     *
     *     2. Prompt Faithfulness Score (0.0 ~ 1.0)
     *     - 응답이 System Prompt를 얼마나 충실히 따랐는지 나타내는 지표
     *     - 1.0 완전 준수, 0.7~0.9 경미한 이탈, 0.7↓ 위반 가능
     *
     *     3. Groundedness Score (0.0 ~ 1.0)
     *     - 응답이 제공된 문서 기반으로 생성되었는지를 나타내는 지표
     *     - 0.8↑ 문서 기반, 0.5~0.8 일부 추론, 0.5↓ 근거 부족
     *
     *     4. Task Alignment Pass (true / false)
     *     - 사용자 요청이 요구한 작업을 제대로 수행했는지를 나타내는 지표
     *     - true  : 요청 의도에 맞는 작업 수행
     *     - false : 작업 미이행 또는 의도 불일치
     *
     *     ---
     *     모델 선택 방법
     *
     *     - gemini-3-flash-preview
     *     - gemini-2.5-pro
     *     - gemini-2.5-flash
     *     - gemini-2.5-flash-lite
     *     - gemini-2.0-flash
     *     - gemini-2.0-flash-lite
     */
    post: operations['generateMemoAiForPlan'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/oauth/google': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 구글 소셜로그인 API
     * @description 구글로 로그인 요청을 전송합니다.
     *     그후 아래 API에 인가코드를 넣어 요청합니다.
     */
    get: operations['redirectToGoogleAuth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/oauth/google/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 구글 인증서버 토큰 검증 API
     * @description 리다이렉트에서 AccessCode를 가지고 서버로 돌아오기 위한 엔드포인트입니다
     *     해당 코드를 이용해서 사용자 정보를 파싱하고 액세스 토큰는 헤더에, 리프레시 토큰은 쿠키에 담아 반환합니다
     */
    get: operations['callback'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/user': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 유저 정보 조회
     * @description 유저 정보를 조회하여, 이름, 이메일, 프로필이미지를 올립니다.
     */
    get: operations['getUserInfo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/memo/{memoId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 메모 전체 조회(모달창)
     * @description 하나의 메모를 상세조회 합니다.
     *     AI가 생성한 메모일 경우 선택한 메모의 ID를 리스트로 반환합니다.
     *     AI가 생성한 메모가 아닐 경우 선택한 메모가 없으므로 빈 리스트를 반환합니다.
     *     라벨은 리스트의 앞부터 우선순위가 높은 순서 입니다.
     */
    get: operations['getOneDetailMemo'];
    put?: never;
    post?: never;
    /**
     * 메모 삭제
     * @description 특정 메모를 삭제합니다.
     */
    delete: operations['deleteMemo'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/memo/structure': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 구조화뷰 메모 전체 조회
     * @description 구조화뷰를 위한 전체 메모를 조회합니다.
     */
    get: operations['getStructureMemo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/label': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 라벨 전체 조회
     * @description 사용자가 생성한 모든 라벨 목록을 조회합니다.
     *     메모에 사용된 라벨과 미사용 라벨을 모두 포함합니다.
     */
    get: operations['getAllLabels'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/chat-rooms/latest': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 최근 AI 채팅방 단일 조회
     * @description 로그인한 사용자의 최근 AI 채팅방을 조회합니다.
     */
    get: operations['findLatestChatRoomByUser'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/access': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 테스트용 액세스 토큰 발급기
     * @description 자체 로그인이 없기 때문에 액세스 토큰이 필요한 경우에 해당 메서드를 이용하여 토큰을 발급 받아주세요
     */
    get: operations['createAccess'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/chat-rooms/{chatRoomId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * AI 채팅방 삭제
     * @description AI 채팅방을 삭제합니다. (Soft Delete)
     */
    delete: operations['deleteChatRoom'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiResponseVoid: {
      /** Format: int32 */
      code?: number;
      msg?: string;
      data?: Record<string, never>;
    };
    ApiResponseString: {
      /** Format: int32 */
      code?: number;
      msg?: string;
      data?: string;
    };
    /** @description 파일 메타데이터 목록 (선택) */
    FileRequest: {
      /**
       * @description S3 key
       * @example memo-file/1/780fd26c-8ab7-4762-b148-b9c8c071795b.pdf
       */
      s3Key?: string;
      /**
       * @description 원본 파일명
       * @example SOPT_7th_seminar.pdf
       */
      fileName?: string;
      /**
       * Format: int64
       * @description 파일 크기(bytes)
       * @example 1048576
       */
      bytes?: number;
      /**
       * @description 확장자
       * @example pdf
       */
      extension?: string;
      /**
       * Format: int32
       * @description 정렬 우선순위
       * @example 0
       */
      priority?: number;
    };
    /** @description 이미지 메타데이터 목록 (선택) */
    ImageRequest: {
      /**
       * @description S3 key
       * @example memo-image/1/53238404-f89d-4728-9dc0-efb2a3c7787b.png
       */
      s3Key?: string;
      /**
       * @description 원본 이미지 파일명
       * @example seminar_slide.png
       */
      imageName?: string;
      /**
       * Format: int64
       * @description 파일 크기(bytes)
       * @example 245678
       */
      bytes?: number;
      /**
       * @description 확장자
       * @example png
       */
      extension?: string;
      /**
       * Format: int32
       * @description 정렬 우선순위
       * @example 0
       */
      priority?: number;
    };
    MemoCreateRequest: {
      /**
       * @description 제목
       * @example SOPT 세미나
       */
      title: string;
      /**
       * @description 내용
       * @example 7차 세미나 내용은 ~가 중요~.
       */
      content: string;
      /**
       * @description 라벨 이름 목록
       * @example [
       *       "SOPT",
       *       "교양",
       *       "레퍼런스"
       *     ]
       */
      labelNames?: string[];
      /** @description 이미지 메타데이터 목록 (선택) */
      images?: components['schemas']['ImageRequest'][];
      /** @description 파일 메타데이터 목록 (선택) */
      files?: components['schemas']['FileRequest'][];
    };
    ApiResponseMemoResponse: {
      /** Format: int32 */
      code?: number;
      msg?: string;
      data?: components['schemas']['MemoResponse'];
    };
    MemoResponse: {
      /**
       * Format: int64
       * @description 메모 ID
       * @example 1
       */
      memoId?: number;
      /**
       * @description 메모 제목
       * @example 세미나 정리
       */
      title?: string;
      /**
       * Format: date-time
       * @description 생성 시각
       */
      createdAt?: string;
    };
    /** @description 메모 이미지/파일 업로드용 presigned URL 발급 요청 */
    MemoPresignedUrlRequest: {
      /**
       * @description 업로드할 이미지 목록
       * @example [
       *       {
       *         "extension": "jpg",
       *         "bytes": 245678,
       *         "priority": 1
       *       },
       *       {
       *         "extension": "png",
       *         "bytes": 532198,
       *         "priority": 2
       *       }
       *     ]
       */
      images: components['schemas']['UploadRequest'][];
      /**
       * @description 업로드할 파일 목록
       * @example [
       *       {
       *         "extension": "pdf",
       *         "bytes": 1048576,
       *         "priority": 1
       *       }
       *     ]
       */
      files: components['schemas']['UploadRequest'][];
    };
    /**
     * @description 단일 파일 업로드 정보
     * @example [
     *       {
     *         "extension": "pdf",
     *         "bytes": 1048576,
     *         "priority": 1
     *       }
     *     ]
     */
    UploadRequest: {
      /**
       * @description 파일 확장자 (확장자만, dot 제외)
       * @example jpg
       */
      extension: string;
      /**
       * Format: int64
       * @description 파일 크기 (bytes)
       * @example 245678
       */
      bytes: number;
      /**
       * Format: int32
       * @description 정렬 우선순위 (낮을수록 앞)
       * @example 1
       */
      priority: number;
    };
    ApiResponseMemoPresignedUrlResponse: {
      /** Format: int32 */
      code?: number;
      msg?: string;
      data?: components['schemas']['MemoPresignedUrlResponse'];
    };
    MemoPresignedUrlResponse: {
      images?: components['schemas']['PresignedUrlResponse'][];
      files?: components['schemas']['PresignedUrlResponse'][];
    };
    PresignedUrlResponse: {
      s3Key?: string;
      presignedUrl?: string;
      /** Format: int64 */
      bytes?: number;
      extension?: string;
      /** Format: int32 */
      priority?: number;
    };
    MemoAiCreateRequest: {
      title: string;
      content: string;
      sourceMemoIds: number[];
    };
    ApiResponseCreateChatRoomResponse: {
      /** Format: int32 */
      code?: number;
      msg?: string;
      data?: components['schemas']['CreateChatRoomResponse'];
    };
    CreateChatRoomResponse: {
      /** Format: int64 */
      chatRoomId?: number;
    };
    MemoAiRequest: {
      userPrompt?: string;
      /** @enum {string} */
      option?: 'MERGE' | 'STRUCTURE' | 'SUMMARY' | 'DEFAULT';
      memoIds: number[];
    };
    ApiResponseMemoAiResponse: {
      /** Format: int32 */
      code?: number;
      msg?: string;
      data?: components['schemas']['MemoAiResponse'];
    };
    MemoAiResponse: {
      title?: string;
      content?: string;
      /** @enum {string} */
      option?: 'MERGE' | 'STRUCTURE' | 'SUMMARY' | 'DEFAULT';
      memoIds?: number[];
      usedPrompt?: string;
    };
    /** @description 플랜 기반 메모 AI 요청 DTO */
    MemoAiRequestForPlan: {
      /**
       * @description 사용자가 입력한 요청 프롬프트
       * @example 유니온파인드 기말시험 공부용으로 핵심만 정리해줘
       */
      userPrompt?: string;
      /**
       * @description AI 처리 옵션
       * @example MERGE
       * @enum {string}
       */
      option?: 'MERGE' | 'STRUCTURE' | 'SUMMARY' | 'DEFAULT';
      /**
       * @description AI가 참조할 메모 ID 목록
       * @example [
       *       43,
       *       44,
       *       45
       *     ]
       */
      memoIds: number[];
      /**
       * @description 플랜에서 정의한 System Prompt
       * @example 너는 컴퓨터공학 전공 시험 대비를 돕는 AI 튜터다.
       *     - 핵심 개념 위주로 정리한다
       *     - 시간 복잡도와 목적을 명확히 설명한다
       *     - 불필요한 장황한 설명은 피한다
       */
      systemPrompt: string;
      /**
       * @description 모델 정의
       * @example gemini-3-flash-preview
       */
      model: string;
      /**
       * Format: double
       * @description temperature 정의
       * @example 0.7
       */
      temperature: number;
    };
    AiEvaluationResult: {
      /** Format: double */
      relevancePass?: number;
      /** Format: double */
      promptFaithfulnessScore?: number;
      /** Format: double */
      groundednessScore?: number;
      taskAlignmentPass?: boolean;
    };
    ApiResponseMemoAiResponseForPlan: {
      /** Format: int32 */
      code?: number;
      msg?: string;
      data?: components['schemas']['MemoAiResponseForPlan'];
    };
    MemoAiResponseForPlan: {
      aiResponse?: components['schemas']['MemoAiResponse'];
      evaluation?: components['schemas']['AiEvaluationResult'];
    };
    ApiResponseUserInfoResponse: {
      /** Format: int32 */
      code?: number;
      msg?: string;
      data?: components['schemas']['UserInfoResponse'];
    };
    UserInfoResponse: {
      /** Format: int64 */
      userId?: number;
      name?: string;
      email?: string;
      profileImageUrl?: string;
    };
    ApiResponseMemoListDashboardResponse: {
      /** Format: int32 */
      code?: number;
      msg?: string;
      data?: components['schemas']['MemoListDashboardResponse'];
    };
    LabelResponse: {
      /** Format: int64 */
      labelId?: number;
      name?: string;
    };
    MemoDashboardResponse: {
      /** Format: int64 */
      memoId?: number;
      title?: string;
      content?: string;
      representativeImageUrl?: string;
      /** Format: int32 */
      imageCount?: number;
      /** Format: int32 */
      fileCount?: number;
      isPinned?: boolean;
      isAiGenerated?: boolean;
      isNew?: boolean;
      /** Format: date-time */
      createdAt?: string;
      labelList?: components['schemas']['LabelResponse'][];
    };
    MemoListDashboardResponse: {
      /** Format: int64 */
      totalCount?: number;
      memos?: components['schemas']['MemoDashboardResponse'][];
    };
    ApiResponseMemoDetailResponse: {
      /** Format: int32 */
      code?: number;
      msg?: string;
      data?: components['schemas']['MemoDetailResponse'];
    };
    /** @description 첨부 파일 정보 */
    FileInfo: {
      /**
       * Format: int64
       * @description 파일 ID
       * @example 1
       */
      fileId?: number;
      /** @description 파일 다운로드 URL (Presigned URL) */
      fileUrl?: string;
      /**
       * @description 파일명
       * @example SOPT_7th_seminar.pdf
       */
      fileName?: string;
      /**
       * @description 파일 확장자
       * @example pdf
       */
      fileExtension?: string;
      /**
       * @description 파일 크기
       * @example 1.00GB
       */
      fileSize?: string;
    };
    /** @description 이미지 정보 */
    ImageInfo: {
      /**
       * Format: int64
       * @description 이미지 ID
       * @example 1
       */
      imageId?: number;
      /** @description 이미지 URL (Presigned URL) */
      imageUrl?: string;
      /**
       * @description 이미지 파일명
       * @example seminar_slide.png
       */
      imageName?: string;
      /**
       * @description 이미지 확장자
       * @example png
       */
      imageExtension?: string;
      /**
       * @description 이미지 크기
       * @example 0.24MB
       */
      imageSize?: string;
    };
    MemoDetailResponse: {
      /**
       * Format: int64
       * @description 메모 ID
       * @example 1
       */
      memoId?: number;
      /**
       * @description 메모 제목
       * @example 집에 빨리 가는 법
       */
      title?: string;
      /**
       * @description 메모 내용
       * @example 발박수 치며 날아 간다.
       */
      content?: string;
      /** @description 이미지 정보 목록 */
      images?: components['schemas']['ImageInfo'][];
      /** @description 첨부 파일 정보 목록 */
      files?: components['schemas']['FileInfo'][];
      /** @description 메모에 딸린 라벨들 */
      labelList?: components['schemas']['LabelResponse'][];
      /**
       * Format: date-time
       * @description 메모 생성 시각
       */
      createdAt?: string;
      /**
       * @description AI 생성 여부
       * @example false
       */
      isAiGenerated?: boolean;
      /**
       * @description AI 생성 시 참고한 메모 제목 목록
       * @example [
       *       "UX 리서치 정리",
       *       "시험 대비 요약"
       *     ]
       */
      sourceMemoTitleList?: string[];
    };
    ApiResponseMemoStructureListResponse: {
      /** Format: int32 */
      code?: number;
      msg?: string;
      data?: components['schemas']['MemoStructureListResponse'];
    };
    MemoStructureListResponse: {
      /** @description 구조화뷰 메모 목록 */
      memos?: components['schemas']['MemoStructureResponse'][];
    };
    /** @description 구조화뷰 메모 목록 */
    MemoStructureResponse: {
      /**
       * Format: int64
       * @description 메모 ID
       * @example 1
       */
      memoId?: number;
      /**
       * @description 메모 제목
       * @example 집에 빨리 가는 법
       */
      title?: string;
      /**
       * @description 메모 내용
       * @example 발박수 치며 날아 간다.
       */
      content?: string;
      /** @description 메모에 딸린 라벨 목록 */
      labelList?: components['schemas']['LabelResponse'][];
    };
    ApiResponseLabelListResponse: {
      /** Format: int32 */
      code?: number;
      msg?: string;
      data?: components['schemas']['LabelListResponse'];
    };
    LabelListResponse: {
      labels?: components['schemas']['LabelResponse'][];
    };
    ApiResponseChatRoomListResponse: {
      /** Format: int32 */
      code?: number;
      msg?: string;
      data?: components['schemas']['ChatRoomListResponse'];
    };
    ChatRoomListResponse: {
      chatRooms?: components['schemas']['ChatRoomResponse'][];
    };
    ChatRoomResponse: {
      /** Format: int64 */
      chatRoomId?: number;
      /** Format: date-time */
      createdAt?: string;
    };
    ApiResponseChatRoomResponse: {
      /** Format: int32 */
      code?: number;
      msg?: string;
      data?: components['schemas']['ChatRoomResponse'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  reissueToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseString'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getMemos: {
    parameters: {
      query?: {
        labelIds?: number[];
        cursorCreatedAt?: string;
        cursorMemoId?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseMemoListDashboardResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  createMemo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MemoCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseMemoResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  issuePresignedUrls: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MemoPresignedUrlRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseMemoPresignedUrlResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getAiMemos: {
    parameters: {
      query?: {
        labelIds?: number[];
        cursorCreatedAt?: string;
        cursorMemoId?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseMemoListDashboardResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  createAiMemo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MemoAiCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseMemoResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getChatRooms: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseChatRoomListResponse'];
        };
      };
    };
  };
  createChatRoom: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseCreateChatRoomResponse'];
        };
      };
    };
  };
  generateMemoAi: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chatRoomId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MemoAiRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseMemoAiResponse'];
        };
      };
    };
  };
  generateMemoAiForPlan: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chatRoomId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MemoAiRequestForPlan'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseMemoAiResponseForPlan'];
        };
      };
    };
  };
  redirectToGoogleAuth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  callback: {
    parameters: {
      query: {
        code: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getUserInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseUserInfoResponse'];
        };
      };
    };
  };
  getOneDetailMemo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        memoId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseMemoDetailResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  deleteMemo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        memoId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getStructureMemo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseMemoStructureListResponse'];
        };
      };
    };
  };
  getAllLabels: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseLabelListResponse'];
        };
      };
    };
  };
  findLatestChatRoomByUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseChatRoomResponse'];
        };
      };
    };
  };
  createAccess: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseString'];
        };
      };
    };
  };
  deleteChatRoom: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chatRoomId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
}
